name: dedis
description: Simple Redis Client for Dart (pubsub and multi/exec commands support)
version: 0.4.1
homepage: https://github.com/SiLeader/dedis
repository: https://github.com/SiLeader/dedis

environment:
  sdk: '>=2.13.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
