name: dedis
description: Simple Redis Client for Dart
version: 0.1.1
homepage: https://github.com/SiLeader/dedis
repository: https://github.com/SiLeader/dedis

environment:
  sdk: '>=2.13.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
